version: 2
updates:
  - package-ecosystem: "maven"
    directories:
      - "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"

