entur:
  jwt:
    enabled: true
    claims:
      expires-at-leeway: 15
      issued-at-leeway: 5
      audiences:
        - https://my.audience
  authorization:
    enabled: true
    permit-all:
      matcher:
        patterns:
          - /actuator/health/**
          - /unprotected
      grpc:
        services:
          - name: org.entur.jwt.spring.demo.grpc.GreetingService
            methods:
              - unprotected
          - name: grpc.health.v1.Health
            methods:
              - "*"

management:
  endpoint:
    health:
      probes:
        enabled: true
