entur:
  jwt:
    enabled: true
    claims:
      expires-at-leeway: 15
      issued-at-leeway: 5
      audiences:
        - https://my.audience
    mdc:
      enabled: true
      mappings:
        - from: iss
          to: issuer
        - from: azp
          to: azp
    jwk:
      health-indicator:
        enabled: true
  authorization:
    enabled: true
    permit-all:
      matcher:
        patterns:
          - /actuator/health
          - /unprotected
  cors:
    enabled: true
    mode: api
    origins:
      - https://my.published.api

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: "readinessState,jwks,accessTokenProvider"