name: Verify master
on:
  push:
    branches:
      - master

jobs:
  verify-main:
    uses: entur/abt-gha-public/.github/workflows/maven-open-source-verify.yml@main

  post-failure-to-slack:
    needs: verify-main
    if: failure()
    uses: entur/gha-slack/.github/workflows/post.yml@v2
    with:
      channel_id: ${{ vars.CHANNEL_ID }}
      message: "🔴 Maven build failed for ${{ github.repository }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    secrets: inherit

  post-success-to-slack:
    needs: verify-main
    if: success()
    uses: entur/gha-slack/.github/workflows/post.yml@v2
    with:
      channel_id: ${{ vars.CHANNEL_ID}}
      message: "🟢 Maven build success for ${{ github.repository }}\n ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    secrets: inherit
